/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.sgu.homecontroller;

import java.awt.SecondaryLoop;

/**
 *
 * @author Ryandy
 */
public class ViewerPanel extends javax.swing.JPanel {
	mainController controllerAC;
	mainController controllerBlinds;
	mainController controllerLamps;
	Time timeObservator;
	Temperature temperatureObservator;
	TimeParser parser = new TimeParser();
    /**
     * Creates new form ViewerPanel
     */
    public ViewerPanel(mainController controllerAC,mainController controllerBlinds,mainController controllerLamps,Time time,Temperature temperature) {
    	this.controllerAC = controllerAC;
        this.controllerBlinds = controllerBlinds;
        this.controllerLamps = controllerLamps;
        this.timeObservator = time;
        this.temperatureObservator = temperature;
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	System.out.println(controllerAC.getStatus());
        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tempOutsideLabel = new javax.swing.JLabel();
        windPressureLabel = new javax.swing.JLabel();
        windOutsideValueLabel = new javax.swing.JLabel();
        tempOutsideValueLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        flagLabel = new javax.swing.JLabel();
        acIndicatorLabel = new javax.swing.JLabel();
        acIndicatorValueLabel = new javax.swing.JLabel();
        descriptionTopLabel = new javax.swing.JLabel();
        descriptionBodyLabel = new javax.swing.JLabel();
        lampIndicatorLabel = new javax.swing.JLabel();
        lampIndicatorValueLabel = new javax.swing.JLabel();
        blindIndicatorLabel = new javax.swing.JLabel();
        blindIndicatorValueLabel = new javax.swing.JLabel();
        roomTemperature = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        blindLabel = new javax.swing.JLabel();
        setTempLabel = new javax.swing.JLabel();
        setTemperatureSpinner = new javax.swing.JSpinner();
        blindButton = new javax.swing.JButton();
        setActiveTimeOnLabel = new javax.swing.JLabel();
        setActiveTimeOffLabel = new javax.swing.JLabel();
        turnOnAcTimeText = new javax.swing.JTextField();
        turnOffAcTimeText = new javax.swing.JTextField();
        submitAcTimeButton = new javax.swing.JButton();
        clearACTimeButton = new javax.swing.JButton();
        setTimeLampLabel = new javax.swing.JLabel();
        lampTimerText = new javax.swing.JTextField();
        submitLampTimerButton = new javax.swing.JButton();
        setOpenBlindTimeLabel = new javax.swing.JLabel();
        setCloseBlindTimeLabel = new javax.swing.JLabel();
        blindOpenTimeText = new javax.swing.JTextField();
        submitBlindTimeButton = new javax.swing.JButton();
        blindCloseTimeText = new javax.swing.JTextField();
        clearBlindTimeButton = new javax.swing.JButton();
        turnOnLampTimeLabel = new javax.swing.JLabel();
        turnOffLampTimeLabel1 = new javax.swing.JLabel();
        turnOnLampTimeText = new javax.swing.JTextField();
        turnOffLampTimeText = new javax.swing.JTextField();
        submitLampTimeButton = new javax.swing.JButton();
        clearLampTimeButton = new javax.swing.JButton();
        OKTempButton = new javax.swing.JButton();
        lampTurnOnLabel = new javax.swing.JLabel();
        lampButton = new javax.swing.JButton();
        acTurnOnLabel = new javax.swing.JLabel();
        acButton = new javax.swing.JButton();

        imagePanel.setPreferredSize(new java.awt.Dimension(350, 250));

        imageLabel.setIcon(new javax.swing.ImageIcon("./Image/Weather/QuestionMark.png")); // NOI18N

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tempOutsideLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tempOutsideLabel.setText("TEMP OUTSIDE        :");

        windPressureLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        windPressureLabel.setText("WIND OUTSIDE        :");

        windOutsideValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        windOutsideValueLabel.setText(".");

        tempOutsideValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tempOutsideValueLabel.setText(".");

        refreshButton.setIcon(new javax.swing.ImageIcon("./Image/Etc/RefreshButton.png")); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        flagLabel.setText("FLAG ICON 140 X 50");

        acIndicatorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        acIndicatorLabel.setText("AC INDICATOR         :");

        acIndicatorValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        if(this.controllerAC.getStatus() == 1) {
        	acIndicatorValueLabel.setText("On");
		}else {
			acIndicatorValueLabel.setText("Off");
		}

        descriptionTopLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionTopLabel.setText("Description");

        descriptionBodyLabel.setBackground(new java.awt.Color(67, 188, 255));
        descriptionBodyLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descriptionBodyLabel.setText("NOTHING TO SHOW");

        lampIndicatorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lampIndicatorLabel.setText("LAMP INDICATOR     :");

        lampIndicatorValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        if(this.controllerLamps.getStatus() == 1) {
        	lampIndicatorValueLabel.setText("On");
		}else {
			lampIndicatorValueLabel.setText("Off");
		}

        blindIndicatorLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        blindIndicatorLabel.setText("BLIND INDICATOR    :");

        blindIndicatorValueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        
        if(this.controllerBlinds.getStatus() == 1) {
			blindIndicatorValueLabel.setText("On");
		}else {
			blindIndicatorValueLabel.setText("Off");
		}

        roomTemperature.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        roomTemperature.setText("0 C");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(acIndicatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tempOutsideLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(windPressureLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(lampIndicatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blindIndicatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(windOutsideValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                        .addComponent(tempOutsideValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(blindIndicatorValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lampIndicatorValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acIndicatorValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(flagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(descriptionBodyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(descriptionTopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tempOutsideLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tempOutsideValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(flagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(descriptionTopLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionBodyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(refreshButton)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(windPressureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(windOutsideValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(acIndicatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acIndicatorValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lampIndicatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lampIndicatorValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(roomTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(blindIndicatorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blindIndicatorValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        blindLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        blindLabel.setText("Blind                     :");

        setTempLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setTempLabel.setText("Set Temperature      :");

        setTemperatureSpinner.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setTemperatureSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                setTemperatureSpinnerStateChanged(evt);
            }
        });

        blindButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        blindButton.setText("Turn On");
        blindButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blindButtonActionPerformed(evt);
            }
        });

        setActiveTimeOnLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setActiveTimeOnLabel.setText("Turn on AC Time     :");

        setActiveTimeOffLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setActiveTimeOffLabel.setText("Turn off AC Time     :");

        turnOnAcTimeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        turnOffAcTimeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        submitAcTimeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitAcTimeButton.setText("SUBMIT");
        submitAcTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAcTimeButtonActionPerformed(evt);
            }
        });

        clearACTimeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearACTimeButton.setText("CLEAR");
        clearACTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearACTimeButtonActionPerformed(evt);
            }
        });

        setTimeLampLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setTimeLampLabel.setText("Set Time               :");

        lampTimerText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        submitLampTimerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitLampTimerButton.setText("SUBMIT");
        submitLampTimerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLampTimerButtonActionPerformed(evt);
            }
        });

        setOpenBlindTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setOpenBlindTimeLabel.setText("Blind Open  Time     :");

        setCloseBlindTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setCloseBlindTimeLabel.setText("Blind Close  Time     :");

        blindOpenTimeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        submitBlindTimeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitBlindTimeButton.setText("SUBMIT");
        submitBlindTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBlindTimeButtonActionPerformed(evt);
            }
        });

        blindCloseTimeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        clearBlindTimeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearBlindTimeButton.setText("CLEAR");
        clearBlindTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBlindTimeButtonActionPerformed(evt);
            }
        });

        turnOnLampTimeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        turnOnLampTimeLabel.setText("Turn on Lamp Time  :");

        turnOffLampTimeLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        turnOffLampTimeLabel1.setText("Turn off Lamp Time  :");

        turnOnLampTimeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        turnOffLampTimeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        submitLampTimeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitLampTimeButton.setText("SUBMIT");
        submitLampTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLampTimeButtonActionPerformed(evt);
            }
        });

        clearLampTimeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearLampTimeButton.setText("CLEAR");
        clearLampTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLampTimeButtonActionPerformed(evt);
            }
        });

        OKTempButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        OKTempButton.setText("OK");
        OKTempButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKTempButtonActionPerformed(evt);
            }
        });

        lampTurnOnLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lampTurnOnLabel.setText("Lamp                    :");

        lampButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lampButton.setText("ON");
        lampButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lampButtonActionPerformed(evt);
            }
        });

        acTurnOnLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        acTurnOnLabel.setText("AC                        :");

        acButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        acButton.setText("ON");
        acButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(setTempLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setTemperatureSpinner))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(acTurnOnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(10, 10, 10)
                                .addComponent(acButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(blindLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lampTurnOnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lampButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(blindButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OKTempButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(setActiveTimeOnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(turnOnAcTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(submitAcTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(setOpenBlindTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blindOpenTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(submitBlindTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(setActiveTimeOffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(turnOffAcTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clearACTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(turnOnLampTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(turnOnLampTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(submitLampTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(setCloseBlindTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(blindCloseTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearBlindTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(turnOffLampTimeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(turnOffLampTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(clearLampTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(setTimeLampLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lampTimerText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(submitLampTimerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OKTempButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setTempLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setActiveTimeOnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(turnOnAcTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(submitAcTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(setOpenBlindTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(blindOpenTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(submitBlindTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(setTemperatureSpinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(blindLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(blindButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setActiveTimeOffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(turnOffAcTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clearACTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(setCloseBlindTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(blindCloseTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearBlindTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lampTurnOnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lampButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acTurnOnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setTimeLampLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(lampTimerText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitLampTimerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(turnOnLampTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnOnLampTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitLampTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(turnOffLampTimeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnOffLampTimeText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearLampTimeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
    	String path = "./Image/Weather/";
    	path +=mControl.returnImage(thermo.getSummary());
    	System.out.println(path);
    	imageLabel.setIcon(new javax.swing.ImageIcon(path)); // NOI18N
    	tempOutsideValueLabel.setText(thermo.doubledValue()+" C");
    	windOutsideValueLabel.setText(baro.doubledValue()+" KPH");
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void submitLampTimerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLampTimerButtonActionPerformed
    	String time = this.lampTimerText.getText();
    	this.timeObservator.setTime(parser.parser(time));
    	if(this.controllerAC.getStatus() == 1) {
    		this.controllerAC.setStatus(0);
    		acIndicatorValueLabel.setText("On");
    		acButton.setText("Turn Off");
    	}else {
    		this.controllerAC.setStatus(1);
    		acIndicatorValueLabel.setText("Off");
    		acButton.setText("Turn On");
    	}
//    	if(blindButton.getText().equals("OPEN")) { //if open do something here
//    		this.controllerBlinds.setStatus(1);
//    		if(this.controllerBlinds.getStatus() == 1) {
//    			blindIndicatorValueLabel.setText("On");
//    		}else {
//    			blindIndicatorValueLabel.setText("Off");
//    		}
//    		blindButton.setText("CLOSE");
//    	}else if(blindButton.getText().equals("CLOSE")){
//    		if(this.controllerBlinds.getStatus() == 0) {
//    			blindIndicatorValueLabel.setText("On");
//    		}else {
//    			blindIndicatorValueLabel.setText("Off");
//    		}
//    		blindButton.setText("OPEN"); //if close do something here
//    	}
    	if(this.controllerBlinds.getStatus() == 1) {
    		this.controllerBlinds.setStatus(0);
    		blindIndicatorValueLabel.setText("On");
    		blindButton.setText("Turn Off");
    	}else {
    		this.controllerBlinds.setStatus(1);
    		blindIndicatorValueLabel.setText("Off");
    		blindButton.setText("Turn On");
    	}
    	if(this.controllerLamps.getStatus() == 1) {
    		this.controllerLamps.setStatus(0);
    		lampIndicatorValueLabel.setText("On");
    		lampButton.setText("Turn Off");
    	}else {
    		this.controllerLamps.setStatus(1);
    		lampIndicatorValueLabel.setText("Off");
    		lampButton.setText("Turn On");
    	}
    	
    }//GEN-LAST:event_submitLampTimerButtonActionPerformed

    private void clearACTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearACTimeButtonActionPerformed
        this.turnOnAcTimeText.setText("");
        this.turnOffAcTimeText.setText("");
        
    }//GEN-LAST:event_clearACTimeButtonActionPerformed

    private void submitAcTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAcTimeButtonActionPerformed
        String onTime = this.turnOnAcTimeText.getText();
        String offTime = this.turnOffAcTimeText.getText();
        this.controllerAC.setTimerOn(onTime);
        this.controllerAC.setTimerOff(offTime);
    }//GEN-LAST:event_submitAcTimeButtonActionPerformed

    private void blindButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blindButtonActionPerformed
        // TODO add your handling code here:

    	if(this.controllerBlinds.getStatus() == 1) {
    		this.controllerBlinds.setStatus(0);
    		blindIndicatorValueLabel.setText("On");
    		blindButton.setText("Turn Off");
    	}else {
    		this.controllerBlinds.setStatus(1);
    		blindIndicatorValueLabel.setText("Off");
    		blindButton.setText("Turn On");
    	}    }//GEN-LAST:event_blindButtonActionPerformed

    private void submitBlindTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBlindTimeButtonActionPerformed
    	String onTime = this.blindOpenTimeText.getText();
        String offTime = this.blindCloseTimeText.getText();
        this.controllerBlinds.setTimerOn(onTime);
        this.controllerBlinds.setTimerOff(offTime);
    }//GEN-LAST:event_submitBlindTimeButtonActionPerformed

    private void clearBlindTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBlindTimeButtonActionPerformed
    	this.blindOpenTimeText.setText("");
        this.blindCloseTimeText.setText("");
    }//GEN-LAST:event_clearBlindTimeButtonActionPerformed

    private void submitLampTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLampTimeButtonActionPerformed
    	String onTime = this.turnOnLampTimeText.getText();
        String offTime = this.turnOffLampTimeText.getText();
        this.controllerLamps.setTimerOn(onTime);
        this.controllerLamps.setTimerOff(offTime);
    }//GEN-LAST:event_submitLampTimeButtonActionPerformed

    private void clearLampTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLampTimeButtonActionPerformed
        this.turnOnLampTimeText.setText("");
        this.turnOffLampTimeText.setText("");
    }//GEN-LAST:event_clearLampTimeButtonActionPerformed

    private void setTemperatureSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_setTemperatureSpinnerStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_setTemperatureSpinnerStateChanged

    private void OKTempButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKTempButtonActionPerformed
        // TODO add your handling code here:
    	roomTemperature.setText(setTemperatureSpinner.getValue()+" C ");
    }//GEN-LAST:event_OKTempButtonActionPerformed

    private void lampButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lampButtonActionPerformed
        // TODO add your handling code here:
    	if(this.controllerLamps.getStatus() == 1) {
    		this.controllerLamps.setStatus(0);
    		lampIndicatorValueLabel.setText("On");
    		lampButton.setText("Turn Off");
    	}else {
    		this.controllerLamps.setStatus(1);
    		lampIndicatorValueLabel.setText("Off");
    		lampButton.setText("Turn On");
    	}
    }//GEN-LAST:event_OKTempButtonActionPerformed


    private void acButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acButtonActionPerformed

        // TODO add your handling code here:
    	if(this.controllerAC.getStatus() == 1) {
    		this.controllerAC.setStatus(0);
    		acIndicatorValueLabel.setText("On");
    		acButton.setText("Turn Off");
    	}else {
    		this.controllerAC.setStatus(1);
    		acIndicatorValueLabel.setText("Off");
    		acButton.setText("Turn On");
    	}
    	
    }//GEN-LAST:event_acButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKTempButton;
    private javax.swing.JButton acButton;
    private javax.swing.JLabel acIndicatorLabel;
    private javax.swing.JLabel acIndicatorValueLabel;
    private javax.swing.JLabel acTurnOnLabel;
    private javax.swing.JButton blindButton;
    private javax.swing.JTextField blindCloseTimeText;
    private javax.swing.JLabel blindIndicatorLabel;
    private javax.swing.JLabel blindIndicatorValueLabel;
    private javax.swing.JLabel blindLabel;
    private javax.swing.JTextField blindOpenTimeText;
    private javax.swing.JButton clearACTimeButton;
    private javax.swing.JButton clearBlindTimeButton;
    private javax.swing.JButton clearLampTimeButton;
    private javax.swing.JLabel descriptionBodyLabel;
    private javax.swing.JLabel descriptionTopLabel;
    private javax.swing.JLabel flagLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lampButton;
    private javax.swing.JLabel lampIndicatorLabel;
    private javax.swing.JLabel lampIndicatorValueLabel;
    private javax.swing.JTextField lampTimerText;
    private javax.swing.JLabel lampTurnOnLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel roomTemperature;
    private javax.swing.JLabel setActiveTimeOffLabel;
    private javax.swing.JLabel setActiveTimeOnLabel;
    private javax.swing.JLabel setCloseBlindTimeLabel;
    private javax.swing.JLabel setOpenBlindTimeLabel;
    private javax.swing.JLabel setTempLabel;
    private javax.swing.JSpinner setTemperatureSpinner;
    private javax.swing.JLabel setTimeLampLabel;
    private javax.swing.JButton submitAcTimeButton;
    private javax.swing.JButton submitBlindTimeButton;
    private javax.swing.JButton submitLampTimeButton;
    private javax.swing.JButton submitLampTimerButton;
    private javax.swing.JLabel tempOutsideLabel;
    private javax.swing.JLabel tempOutsideValueLabel;
    private javax.swing.JTextField turnOffAcTimeText;
    private javax.swing.JLabel turnOffLampTimeLabel1;
    private javax.swing.JTextField turnOffLampTimeText;
    private javax.swing.JTextField turnOnAcTimeText;
    private javax.swing.JLabel turnOnLampTimeLabel;
    private javax.swing.JTextField turnOnLampTimeText;
    private javax.swing.JLabel windOutsideValueLabel;
    private javax.swing.JLabel windPressureLabel;
    
    private Sensor thermo = new Thermometer();
    private Sensor baro = new Barometer();
    private mainController mControl = new mainController();
    // End of variables declaration//GEN-END:variables
}
